### ISSUE TITLE
Throwing nodemailer error

### ISSUE THREAD

**Issue by lee-40square** [alykoshin/gmail-send#2]
With just these two lines

```
'use strict';
var sendGmail = require('gmail-send');
```

I get this

```
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/leejohnson/dev/repo/fo-website-foundation/node_modules/nodemailer/lib/nodemailer.js:3:16)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
```

It throws the same error when I follow the code sample. I'm running node 5.3.0

**Comment by lee-40square** [comment]
I just checked and looks like nodemailer requires 6+. I will confirm that's the problem.

**Comment by lee-40square** [comment]
That was the problem.

**Comment by alykoshin** [comment]
Yes, it seems to be ES6 syntax, not supported by early Node.
