### ISSUE TITLE
Error: Self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by IverBand** [alykoshin/gmail-send#7]
Hi,

I am getting this error running ECMAScript 6 and have required the Alexa Skills Kit, since I am putting various pieces together that will eventually be an Alexa Skill.  I am trying to send from a gmail address that does not have two-step authentication enabled.  

I am a relative newbie at this.  Any help would be appreciated.

Iver

Error: PE0030 email send failed. Returned error: Error: self signed certificate in certificate chain and result: undefined
    at C:\Users\User\Dropbox\_WebStormProjects\PE\lambda\custom\main.js:90:15
    at C:\Users\User\Dropbox\_WebStormProjects\PE\lambda\custom\node_modules\gmail-send\index.js:120:9
    at transporter.send (C:\Users\User\Dropbox\_WebStormProjects\PE\lambda\custom\node_modules\nodemailer\lib\mailer\index.js:224:21)
    at SMTPConnection.connection.once.err (C:\Users\User\Dropbox\_WebStormProjects\PE\lambda\custom\node_modules\nodemailer\lib\smtp-transport\index.js:174:24)
    at SMTPConnection.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at SMTPConnection.emit (events.js:188:7)
    at SMTPConnection._onError (C:\Users\User\Dropbox\_WebStormProjects\PE\lambda\custom\node_modules\nodemailer\lib\smtp-connection\index.js:567:14)
    at TLSSocket._socket.on.err (C:\Users\User\Dropbox\_WebStormProjects\PE\lambda\custom\node_modules\nodemailer\lib\smtp-connection\index.js:257:18)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by alykoshin** [comment]
Maybe you are connecting to something with `self signed certificate` instead of actual GMail server..?

**Comment by IverBand** [comment]
How is the server destination configured? How can I check that? I am writing a node.js client that closely mirrors the example in the README.

**Comment by IverBand** [comment]
Figured it out.  Thanks.

**Comment by Roguyt** [comment]
Could you explain what was the issue ? I'm facing the same problem and i'm mirroring the code of demo so i'm a bit lost on what's the problem :/
Thanks

**Comment by crostine** [comment]
can you share?
